import { describe, expect, it } from "vitest";
import { generateKid, verifyKid } from "@/lib/kid";

describe("generateKid", () => {
  it("strips the dash and produces an 11-digit KID", () => {
    const kid = generateKid("2026-000001");
    expect(kid).toMatch(/^\d{11}$/);
    expect(kid.slice(0, 10)).toBe("2026000001");
  });

  it("produces an 11-digit KID for the standard year+sequence format", () => {
    const kid = generateKid("2026-000042");
    expect(kid).toHaveLength(11);
    expect(/^\d{11}$/.test(kid)).toBe(true);
  });

  it("produces deterministic output (same input -> same KID)", () => {
    const a = generateKid("2026-000123");
    const b = generateKid("2026-000123");
    expect(a).toBe(b);
  });

  it("differs by exactly the trailing check digit when only the sequence changes", () => {
    const k1 = generateKid("2026-000001");
    const k2 = generateKid("2026-000002");
    // First 10 digits match the unhyphenated input, only the check digit can
    // differ between sequential invoices.
    expect(k1.slice(0, 10)).toBe("2026000001");
    expect(k2.slice(0, 10)).toBe("2026000002");
  });
});

describe("verifyKid", () => {
  it("verifies a KID generated by generateKid", () => {
    const kid = generateKid("2026-000001");
    expect(verifyKid(kid)).toBe(true);
  });

  it("rejects a KID with a flipped check digit", () => {
    const valid = generateKid("2026-000001");
    const lastDigit = parseInt(valid.slice(-1), 10);
    const flipped = valid.slice(0, -1) + String((lastDigit + 1) % 10);
    expect(verifyKid(flipped)).toBe(false);
  });

  it("rejects a KID shorter than 2 digits", () => {
    expect(verifyKid("")).toBe(false);
    expect(verifyKid("1")).toBe(false);
  });

  it("round-trips: every generated KID verifies", () => {
    for (let seq = 1; seq <= 20; seq++) {
      const num = `2026-${String(seq).padStart(6, "0")}`;
      const kid = generateKid(num);
      expect(verifyKid(kid)).toBe(true);
      expect(kid).toMatch(/^\d{11}$/);
    }
  });
});
